[package]
name = "grainsquery"
version = "0.1.0"
authors = ["Alexander Thaller <alexander.thaller@trivago.com>"]

[dependencies]
serde = "^0.7"
serde_macros = "^0.7"
serde_yaml = "^0.2"
glob = "*"
log = "0.3"
loggerv = "0.2.0"
env_logger = "0.3"
regex = "0.1"

[dependencies.clap]
version = "2"
features = ["yaml"]
