[package]
name = "grainsquery"
version = "0.1.0"
authors = ["Alexander Thaller <alexander.thaller@trivago.com>"]

[dependencies]
serde = "*"
serde_macros = "*"
serde_yaml = "*"
serde_json = "*"
glob = "*"
log = "*"
loggerv = "*"
env_logger = "*"
regex = "*"
time = "*"

[dependencies.clap]
version = "*"
features = ["yaml"]
